### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [jeetelongname/Yeet-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by jeetelongname** [comment]
Hey thanks for your interest!, I have added the screenshots and this has also given me an excuse to get rid of that oh my zsh dependency! Do send me a link when it goes up!
